// ============================================================
// SynoChain AI 内容生成脚本 (Phase 2)
// 功能：读取待处理关键词，调用 OpenAI 生成 SEO 文章，保存到数据库
// 用法：node scripts/generate-content.js --type=disease --limit=10 --lang=en
// ============================================================

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ---------- 简易 .env 加载器（无需 dotenv 依赖） ----------
function loadEnvFile() {
  try {
    const envPath = resolve(__dirname, '..', '.env');
    const content = readFileSync(envPath, 'utf-8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex === -1) continue;
      const key = trimmed.slice(0, eqIndex).trim();
      let value = trimmed.slice(eqIndex + 1).trim();
      // 去除两侧引号
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      if (!process.env[key]) {
        process.env[key] = value;
      }
    }
  } catch {
    // 没有 .env 文件，忽略
  }
}

loadEnvFile();

// ---------- 配置 ----------
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY || '';
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';

const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';
const OPENAI_MODEL = 'gpt-4';
const MAX_RETRIES = 3;

// ---------- 命令行参数解析 ----------
function parseArgs() {
  const args = { type: null, limit: 10, lang: 'en' };
  for (const arg of process.argv.slice(2)) {
    if (arg.startsWith('--type=')) args.type = arg.slice(7);
    else if (arg.startsWith('--limit=')) args.limit = parseInt(arg.slice(8), 10) || 10;
    else if (arg.startsWith('--lang=')) args.lang = arg.slice(7);
  }
  return args;
}

// ---------- 日志工具 ----------
const log = {
  info: (msg) => console.log(`[INFO] ${new Date().toISOString()} - ${msg}`),
  success: (msg) => console.log(`[SUCCESS] ${new Date().toISOString()} - ${msg}`),
  warn: (msg) => console.warn(`[WARN] ${new Date().toISOString()} - ${msg}`),
  error: (msg) => console.error(`[ERROR] ${new Date().toISOString()} - ${msg}`),
};

// ---------- 读取本地提示词模板文件 ----------
const PROMPT_FILE_MAP = {
  disease: 'disease.txt',
  symptom: 'symptom.txt',
  question: 'faq.txt',
};

function readLocalPrompt(type) {
  try {
    const filePath = resolve(__dirname, '..', 'prompts', PROMPT_FILE_MAP[type] || PROMPT_FILE_MAP.disease);
    return readFileSync(filePath, 'utf-8');
  } catch (err) {
    log.warn(`无法读取本地提示词文件: ${err.message}`);
    return null;
  }
}

// ---------- Mock 数据（无 API key 时演示用） ----------
function getMockArticle(keyword, type) {
  log.info(`使用 mock 数据生成文章: "${keyword}" (type=${type})`);
  return {
    title: `${keyword.charAt(0).toUpperCase() + keyword.slice(1)} - Complete Guide`,
    meta_description: `Learn everything about ${keyword}: causes, symptoms, treatments and prevention. Expert-reviewed health information.`,
    summary: `A comprehensive overview of ${keyword}, covering causes, symptoms, treatment options and prevention strategies.`,
    content: `## Overview\n\nThis is a mock article about ${keyword}. In production, this content would be generated by OpenAI.\n\n## Causes\n\nMock causes content for ${keyword}.\n\n## Symptoms\n\nMock symptoms content.\n\n## Treatments\n\nMock treatments content.\n\n## Prevention\n\nMock prevention content.\n\n---\n\n*Disclaimer: This content is for informational purposes only and not a substitute for professional medical advice.*`,
    faq: [
      {
        question: `What is ${keyword}?`,
        answer: `This is a mock answer about ${keyword}.`,
      },
      {
        question: `How is ${keyword} treated?`,
        answer: `This is a mock answer about treatments for ${keyword}.`,
      },
    ],
  };
}

// ---------- 调用 OpenAI API（带重试） ----------
async function callOpenAI(prompt, retries = MAX_RETRIES) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      log.info(`调用 OpenAI API (第 ${attempt}/${retries} 次尝试)...`);
      const response = await fetch(OPENAI_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${OPENAI_API_KEY}`,
        },
        body: JSON.stringify({
          model: OPENAI_MODEL,
          messages: [
            {
              role: 'system',
              content: 'You are a professional medical content writer. Always respond with valid JSON only.',
            },
            { role: 'user', content: prompt },
          ],
          temperature: 0.7,
          response_format: { type: 'json_object' },
        }),
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`OpenAI API ${response.status}: ${errText}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content;
      if (!content) throw new Error('OpenAI 返回内容为空');

      const parsed = JSON.parse(content);
      log.success('OpenAI API 调用成功');
      return parsed;
    } catch (err) {
      log.error(`第 ${attempt} 次尝试失败: ${err.message}`);
      if (attempt === retries) throw err;
      // 指数退避
      const waitMs = 1000 * Math.pow(2, attempt - 1);
      log.info(`等待 ${waitMs}ms 后重试...`);
      await new Promise((r) => setTimeout(r, waitMs));
    }
  }
}

// ---------- 生成单篇文章 ----------
async function generateArticle(keyword, type, useMock) {
  // 优先使用本地提示词文件，回退到数据库模板
  let promptTemplate = readLocalPrompt(type);
  if (!promptTemplate) {
    throw new Error('未找到可用的提示词模板');
  }
  const prompt = promptTemplate.replace(/\{\{keyword\}\}/g, keyword);

  if (useMock) {
    return getMockArticle(keyword, type);
  }

  const article = await callOpenAI(prompt);
  // 校验结构完整性
  const required = ['title', 'meta_description', 'summary', 'content', 'faq'];
  for (const field of required) {
    if (!(field in article)) {
      log.warn(`生成内容缺少字段: ${field}，使用默认值`);
      article[field] = field === 'faq' ? [] : '';
    }
  }
  if (!Array.isArray(article.faq)) article.faq = [];
  return article;
}

// ---------- 生成 slug ----------
function slugify(text) {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

// ---------- 主流程（Mock 模式） ----------
async function runMock(args) {
  log.warn('未检测到 SUPABASE_URL / SUPABASE_SERVICE_KEY / OPENAI_API_KEY，使用 mock 模式演示流程');
  log.info(`参数: type=${args.type || 'all'}, limit=${args.limit}, lang=${args.lang}`);

  const mockKeywords = [
    { id: 'mock-1', keyword: 'sinusitis', type: 'disease', language: 'en' },
    { id: 'mock-2', keyword: 'migraine', type: 'disease', language: 'en' },
    { id: 'mock-3', keyword: 'headache', type: 'symptom', language: 'en' },
    { id: 'mock-4', keyword: 'fatigue', type: 'symptom', language: 'en' },
    { id: 'mock-5', keyword: 'how to lower blood pressure', type: 'question', language: 'en' },
  ].filter((k) => !args.type || k.type === args.type).slice(0, args.limit);

  log.info(`找到 ${mockKeywords.length} 个待处理关键词（mock）`);

  for (const kw of mockKeywords) {
    log.info(`---- 处理关键词: "${kw.keyword}" (type=${kw.type}) ----`);
    try {
      const article = await generateArticle(kw.keyword, kw.type, true);
      log.success(`Mock 文章生成成功: "${article.title}"`);
      log.info(`  slug: ${slugify(kw.keyword)}`);
      log.info(`  meta_description: ${article.meta_description}`);
      log.info(`  FAQ 数量: ${article.faq.length}`);
      log.info(`  [模拟] 保存到 generated_contents 表`);
      log.info(`  [模拟] 更新 keywords 表 status -> completed`);
    } catch (err) {
      log.error(`关键词 "${kw.keyword}" 处理失败: ${err.message}`);
    }
  }
  log.success('Mock 流程完成');
}

// ---------- 主流程（生产模式） ----------
async function runProduction(args) {
  log.info('使用 Supabase + OpenAI 生产模式');
  log.info(`参数: type=${args.type || 'all'}, limit=${args.limit}, lang=${args.lang}`);

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
    auth: { persistSession: false },
  });

  // 查询待处理关键词
  let query = supabase
    .from('keywords')
    .select('id, keyword, type, language, status')
    .eq('status', 'pending')
    .eq('language', args.lang)
    .order('created_at', { ascending: true })
    .limit(args.limit);

  if (args.type) {
    query = query.eq('type', args.type);
  }

  const { data: keywords, error: kwError } = await query;

  if (kwError) {
    log.error(`查询 keywords 失败: ${kwError.message}`);
    process.exit(1);
  }

  if (!keywords || keywords.length === 0) {
    log.info('没有待处理的关键词');
    return;
  }

  log.info(`找到 ${keywords.length} 个待处理关键词`);

  // 查询 ai_prompts 模板（备用，优先使用本地文件）
  const { data: prompts, error: promptError } = await supabase
    .from('ai_prompts')
    .select('name, type, template')
    .eq('is_active', true);
  if (promptError) {
    log.warn(`查询 ai_prompts 失败（将使用本地模板）: ${promptError.message}`);
  } else {
    log.info(`加载了 ${prompts?.length || 0} 个提示词模板`);
  }

  let successCount = 0;
  let failCount = 0;

  for (const kw of keywords) {
    log.info(`---- 处理关键词: "${kw.keyword}" (id=${kw.id}, type=${kw.type}) ----`);

    // 标记为 processing
    await supabase.from('keywords').update({ status: 'processing' }).eq('id', kw.id);

    try {
      const article = await generateArticle(kw.keyword, kw.type, false);
      const slug = slugify(kw.keyword);

      // 保存到 generated_contents
      const { data: saved, error: saveError } = await supabase
        .from('generated_contents')
        .insert({
          keyword_id: kw.id,
          type: kw.type,
          slug,
          title: article.title,
          meta_description: article.meta_description,
          summary: article.summary,
          content: article.content,
          faq: article.faq,
          language: kw.language || args.lang,
          ai_model: OPENAI_MODEL,
          status: 'draft',
        })
        .select('id')
        .single();

      if (saveError) {
        throw new Error(`保存 generated_contents 失败: ${saveError.message}`);
      }

      log.success(`文章已保存 (id=${saved.id}): "${article.title}"`);
      log.info(`  slug: ${slug}`);
      log.info(`  FAQ 数量: ${article.faq.length}`);

      // 更新关键词状态为 completed
      const { error: updError } = await supabase
        .from('keywords')
        .update({ status: 'completed' })
        .eq('id', kw.id);

      if (updError) {
        log.warn(`更新 keywords 状态失败: ${updError.message}`);
      } else {
        log.success(`关键词 "${kw.keyword}" 状态已更新为 completed`);
      }
      successCount++;
    } catch (err) {
      log.error(`关键词 "${kw.keyword}" 生成失败: ${err.message}`);
      // 失败回退为 pending（以便下次重试）
      await supabase.from('keywords').update({ status: 'pending' }).eq('id', kw.id);
      failCount++;
    }
  }

  log.info(`========== 任务完成 ==========`);
  log.info(`成功: ${successCount} / 失败: ${failCount} / 总计: ${keywords.length}`);
}

// ---------- 入口 ----------
async function main() {
  const args = parseArgs();
  log.info('SynoChain AI 内容生成脚本启动');
  log.info(`参数: type=${args.type || 'all'}, limit=${args.limit}, lang=${args.lang}`);

  const isConfigured = Boolean(SUPABASE_URL && SUPABASE_SERVICE_KEY && OPENAI_API_KEY);

  if (!isConfigured) {
    await runMock(args);
  } else {
    await runProduction(args);
  }
}

main().catch((err) => {
  log.error(`脚本异常退出: ${err.message}`);
  process.exit(1);
});
